[client]
remoteHost=192.168.1.241
xdpRestoreToken=Yr5IK7ahv7Vfx_LlARWdKA

[core]
computerName=fedora
coreMode=2
language=en
lastVersion=1.26.0.0
port=24800
preventSleep=false
processMode=1
wlClipboard=true

[daemon]
elevate=true

[gui]
autoHide=false
closeReminder=false
closeToTray=true
enableUpdateCheck=false
logExpanded=true
showVersionInTitle=false
shownFirstConnectedMessage=true
shownServerFirstStartMessage=true
startCoreWithGui=false
symbolicTrayIcon=true

[internalConfig]
clipboardSharing=false
clipboardSharingSize=@Variant(\0\0\0\x84\0\0\0\0\0\0\f\0)
defaultLockToScreenState=false
disableLockToScreen=false
hasHeartbeat=false
hasSwitchDelay=false
hasSwitchDoubleTap=false
heartbeat=5000
hotkeys\size=0
numColumns=5
numRows=3
protocol=1
relativeMouseMoves=false
screens\1\name=
screens\10\name=
screens\11\name=
screens\12\name=
screens\13\name=
screens\14\name=
screens\15\name=
screens\2\name=
screens\3\name=
screens\4\name=
screens\5\name=
screens\6\aliasArray\size=0
screens\6\fixArray\1\fix=false
screens\6\fixArray\2\fix=false
screens\6\fixArray\3\fix=false
screens\6\fixArray\4\fix=false
screens\6\fixArray\size=4
screens\6\modifierArray\1\modifier=0
screens\6\modifierArray\2\modifier=1
screens\6\modifierArray\3\modifier=2
screens\6\modifierArray\4\modifier=3
screens\6\modifierArray\5\modifier=4
screens\6\modifierArray\6\modifier=5
screens\6\modifierArray\size=6
screens\6\name=fedora
screens\6\switchCornerArray\1\switchCorner=false
screens\6\switchCornerArray\2\switchCorner=false
screens\6\switchCornerArray\3\switchCorner=false
screens\6\switchCornerArray\4\switchCorner=false
screens\6\switchCornerArray\size=4
screens\6\switchCornerSize=0
screens\7\aliasArray\size=0
screens\7\fixArray\1\fix=false
screens\7\fixArray\2\fix=false
screens\7\fixArray\3\fix=false
screens\7\fixArray\4\fix=false
screens\7\fixArray\size=4
screens\7\modifierArray\1\modifier=0
screens\7\modifierArray\2\modifier=1
screens\7\modifierArray\3\modifier=2
screens\7\modifierArray\4\modifier=3
screens\7\modifierArray\5\modifier=4
screens\7\modifierArray\6\modifier=5
screens\7\modifierArray\size=6
screens\7\name=ABDL-Jimmy
screens\7\switchCornerArray\1\switchCorner=false
screens\7\switchCornerArray\2\switchCorner=false
screens\7\switchCornerArray\3\switchCorner=false
screens\7\switchCornerArray\4\switchCorner=false
screens\7\switchCornerArray\size=4
screens\7\switchCornerSize=0
screens\8\name=
screens\9\name=
screens\size=15
switchCornerArray\1\switchCorner=false
switchCornerArray\2\switchCorner=false
switchCornerArray\3\switchCorner=false
switchCornerArray\4\switchCorner=false
switchCornerArray\size=4
switchCornerSize=0
switchDelay=250
switchDoubleTap=250
win32KeepForeground=false

[log]
file=/home/ypathan/deskflow.log
guiDebug=false
level=4
toFile=false

[security]
certificate=/home/ypathan/.config/Deskflow/tls/deskflow.pem
checkPeerFingerprints=true
keySize=2048
tlsEnabled=false

[server]
externalConfig=false
externalConfigFile=/home/ypathan/.config/Deskflow/deskflow-server.conf
