section: screens
	fedora:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	ABDL-Jimmy:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	fedora:
		right = ABDL-Jimmy
	ABDL-Jimmy:
		left = fedora
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = false
	clipboardSharingSize = 3072
	switchCorners = none 
	switchCornerSize = 0
end

